### ISSUE TITLE
chart-fx x.1.0 roadmap

### ISSUE THREAD

**Issue by wirew0rm** [GSI-CS-CO/chart-fx#38]
Roadmap of changes for the next release of chartfx (x.1.0):

General:
- [x] Replace all occurences of system.out with slf4j
- [x] Use simple default slf4j Configuration for tests and samples. Documentation for library users.
- [x] Travis: allow CI (without deploy) for Pull Requests, check Tag for correct version format, make sure every tag is built

DataSet:
- [x] move from simple lock to (optimistic) ReadWriteLock
- [x] remove undefVlaue from DataSet
- [x] AxisDescription Interface
DataSet
  - [x] Move getXValues/getYValues to dataSet2D
- [x] TreeDataSet: fix indexing bugs for labels and styles
- [x] Serializer

Chart:
- [x] Hide/Show plugin-toolbar without rescaling the chart
- [x] MountainRangeRenderer: Fix zoom issues
- [x] Renderer: Allow charts to be displayed transposed
- [x] Improve DataViewer [low priority]

Math:
- [x] IIR/FIR filters: constructors should be static methods
- math library -> moved to #44 
    - requirements: xi²-fit, matrix, svd, complex, gauss
    - candidates: apache-commons-math, smile, netlibs(ATLAS via JNI)

**Comment by ennerf** [comment]
Are the math libraries a selection of what you're already familiar with / using internally, or are you evaluating different projects?

If you're still evaluating alternatives, it may also be worth also taking a look at [EJML](http://ejml.org/) and its' sister libraries [DDogleg](http://ddogleg.org/) and [GeoRegression](http://georegression.org/). The APIs and performance are very good and they're very extensible.

**Comment by RalphSteinhagen** [comment]
@ennerf thank you very much for the recommendation. We will take them into consideration.

Since about 2005 we used to use a mixture of JAMA (obsolete), Parallel-Colt (also obsolete), custom fitter (yes, we/I want to get rid of that) and apache-commons-math (maturity of all sub-functionality wasn't clear in the earlier version).

Looking primarily for a robust/fast linear-algebra package and xi²-fit functionality (+ consistent/non-colliding function definition). This one of the reasons why we haven't tackled the 'math' package much. Unfortunately, the eco-system in Java seems to be a bit more scarce than in the e.g. C/C++ world.

This issue is an experiment intended to open our internal processes a bit and to invite constructive feedback from the world ... thus your comment is much appreciated. Thanks.

**Comment by ennerf** [comment]
The [Java Matrix Benchmark](https://lessthanoptimal.github.io/Java-Matrix-Benchmark/) (written by the EJML author) has an overview of all the common Java math libraries. [OJAlgo](https://www.ojalgo.org/) looks interesting as well, but so far I haven't had any experience with it.

**Comment by RalphSteinhagen** [comment]
Call for last round ... we are about to close the feature list for this x.1.0 release cycle.  

Thanks a lot to @ennerf  and @wirew0rm for your input, contributions, tests a bug-fixes.

Started final testing/integration in view of pull to master and JDK8 and eventual release (~end of this week). Featured not covered in this release were shifted to #44 

Please let us know if there are issues (especially bugs) that need to be addressed beforehand.

**Comment by ennerf** [comment]
I've done a release of our plotting tool a few weeks ago, but users ended up preferring the old version. This was primarily due to (1) issues with rendering dashed lines, and (2) users being confused by `nan` lines at the bottom.

It'd be great if you could add a configuration option to render `nan` normally, even if it incurs the performance penalty. If I remember right it required a fork to change the `nan => min_value` replacement.

**Comment by RalphSteinhagen** [comment]
@ennerf since you helped us a lot with your bug reports and suggestions... 
our code monkey has granted you ~~three~~ two wishes. :grin:

> It'd be great if you could add a configuration option to render nan [..]
N.B. as mentioned earlier: the 'NaN=>min_value' mapping was necessary since the older JDK8/JavaFX/GPU engine tended to crash when pushing too many NaN into the pipeline. 

Anyway, I added a flag `allowNaNsProperty()' to the ErrorDataSetRenderer to control the behaviour for (2), and extended/implemented the `DataSet::setStyle(..)` parsing interface regarding dashed lines (1). For the time being, the flag default value is being 'false' but could be switched to 'true' once the previous issue doesn't reappear and the overall performance is deemed acceptable by my colleagues. JDK11++ seems to be unaffected.

Have a look at the [NotANumberSample](https://github.com/GSI-CS-CO/chart-fx/blob/dev-x.1.0/chartfx-samples/src/main/java/de/gsi/chart/samples/NotANumberSample.java). 
![image](https://user-images.githubusercontent.com/46007894/68342431-df7bc800-00ea-11ea-9925-5a7ba8e57ecd.png)

Regarding performance: haven't done detailed tests yet, but the performance penalty does not seem to be too severe. The difference for 200 kPoints@25 Hz seems to be ~80% (w/o) to 92% (w/ NaN functionality) on my specific (older) CPU. Maybe someone can improve upon this since I focused more on the correct functionality than performance for this iteration:
![image](https://user-images.githubusercontent.com/46007894/68342272-8a3fb680-00ea-11ea-969b-1b385a548806.png)

If you could have a look and let us know if this helps your purpose.

**Comment by ennerf** [comment]
Thank you! I'm at a conference this week, but I'll try to find some time to test it.

I set the dashed array via styles, but the issue was that they render like a solid line when points are too close. See [Scope #90](https://github.com/HebiRobotics/hebi-scope-feedback/issues/90). Would the change fix this?

**Comment by RalphSteinhagen** [comment]
yes, b45abf7 also addresses [Scope #90](https://github.com/HebiRobotics/hebi-scope-feedback/issues/90) and statements like `dataSet1.setStyle("strokeDashPattern= 25, 20, 5, 20;");`being now being correctly passed through to JavaFX's `GraphicsContext` rendering pipe-line.

So far I have tested only the correct functioning but not the (possible) line-drawing performance penalty in detail.

Enjoy!

**Comment by RalphSteinhagen** [comment]
released new ChartFx version [[8,11].1.0](https://github.com/GSI-CS-CO/chart-fx/releases/tag/11.1.0).

This closes this issue. Please let us know if you find bugs, missing features, or have any
questions regarding library usage etc.

Larger new (API changing) features to be collected in #44

**Comment by ennerf** [comment]
Sorry for the delay. I finally got a chance to test it and so far everything looks good. Thanks again!
