### ISSUE TITLE
chart-fx x.2.0 roadmap

### ISSUE THREAD

**Issue by RalphSteinhagen** [GSI-CS-CO/chart-fx#44]
Roadmap of changes for the next release of chartfx (x.2.0):

Leftovers from #38 ... to be extended (contributions are welcome)

General:
- [x] modularisation, see also #160 
- [x] change licensing model from Apache 2.0 to LGPL v3.0
- [x] remove `@Deprecated` marked API
- [x] reduce code dupplication and refactoring of utility methods
- [x] improve JUnit 5 test coverage
- [ ] Curated docs (beginner -> advanced)
- [ ] remove verbose logging esp. in tests

DataSet:
- [x] Make DataSet multi dimension capable, DataSet2D and DataSet3D on same level below DataSet
- [x] remove `DataSet::getDataCount(int)` interface method (as above)
- [ ] ~Sorted Flag in DataSet?~
- [ ] SerializedDataSet (zeroCopy, in-place deserialisation) [low priority]

Chart:
- [x] move from usage SVG (Batik-) to fonts (Ikonli-based)
- [x] Add dimension to axis interface instead of using the position in axis list and its side (needed e.g. to display color axis below chart)

Math:
- [ ] ~math library~
    - requirements: xi²-fit, matrix, svd, complex, gauss
    - candidates: [apache-commons-math](http://commons.apache.org/proper/commons-math/), [smile](https://github.com/haifengl/smile), [ejml](https://ejml.org/), [ojAlgo](https://www.ojalgo.org/)
